Repository brain-tec/bank-payment, pull requests merged in 2019-04, with the labels that each got.

#299 Syncing from upstream OCA/bank-payment (10.0)
  account_banking_sepa_credit_transfer/tests/test_sct.py
Labels: 10.0

#300 Syncing from upstream OCA/bank-payment (12.0)
  account_payment_order_return/README.rst
  account_payment_order_return/__init__.py
  account_payment_order_return/__manifest__.py
  account_payment_order_return/i18n/account_payment_order_return.pot
  account_payment_order_return/i18n/ca.po
  account_payment_order_return/i18n/de.po
  account_payment_order_return/i18n/es.po
  account_payment_order_return/i18n/fr.po
  account_payment_order_return/readme/CONTRIBUTORS.rst
  account_payment_order_return/readme/DESCRIPTION.rst
  account_payment_order_return/readme/INSTALL.rst
  account_payment_order_return/readme/USAGE.rst
  account_payment_order_return/static/description/icon.png
  account_payment_order_return/static/description/index.html
  account_payment_order_return/tests/__init__.py
  account_payment_order_return/tests/test_account_payment_order_return.py
  account_payment_order_return/wizards/__init__.py
  account_payment_order_return/wizards/account_payment_line_create.py
  account_payment_order_return/wizards/account_payment_line_create_view.xml
  oca_dependencies.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/account_payment_order_return/odoo/addons/account_payment_order_return
  setup/account_payment_order_return/setup.py
Labels: 12.0

#301 Syncing from upstream OCA/bank-payment (8.0)
  account_payment_transfer_reconcile_batch/static/description/icon.png
Labels: 8.0

#302 Syncing from upstream OCA/bank-payment (9.0)
  account_banking_mandate_sale/static/description/icon.png
  account_payment_mode/static/description/icon.png
  account_payment_transfer_reconcile_batch/static/description/icon.png
Labels: 9.0

#303 Syncing from upstream OCA/bank-payment (10.0)
  account_banking_mandate_sale/static/description/icon.png
  account_payment_line_cancel/static/description/icon.png
  account_payment_mode/static/description/icon.png
Labels: 10.0

#304 Syncing from upstream OCA/bank-payment (12.0)
  account_banking_sepa_direct_debit/i18n/it.po
Labels: 12.0

#305 Syncing from upstream OCA/bank-payment (11.0)
  account_payment_order/__manifest__.py
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/models/account_invoice.py
  account_payment_order/models/account_move.py
  account_payment_order/models/account_move_line.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/models/account_payment_mode.py
  account_payment_order/models/account_payment_order.py
  account_payment_order/models/bank_payment_line.py
  account_payment_order/models/res_bank.py
  account_payment_order/wizard/account_invoice_payment_line_multi.py
  account_payment_order/wizard/account_payment_line_create.py
Labels: 11.0

#306 Syncing from upstream OCA/bank-payment (12.0)
  account_banking_mandate/i18n/it.po
  account_payment_order/i18n/it.po
Labels: 12.0

#307 Syncing from upstream OCA/bank-payment (12.0)
  account_payment_order/report/account_payment_order.py
Labels: 12.0

#309 Syncing from upstream OCA/bank-payment (12.0)
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/models/account_payment_order.py
Labels: 12.0

#308 [t114249] SEPA together with other Swiss payments
  account_banking_pain_base/models/account_payment_order.py
  account_banking_pain_base/views/account_payment_order.xml
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/models/__init__.py
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_credit_transfer/models/bank_payment_line.py
  account_banking_sepa_credit_transfer/views/bank_payment_line.xml
Labels: 11.0.project_pr_449

#310 Syncing from upstream OCA/bank-payment (12.0)
  account_banking_mandate/i18n/it.po
  account_banking_pain_base/i18n/it.po
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/report/account_payment_order.xml
Labels: 12.0

#311 Syncing from upstream OCA/bank-payment (11.0)
  account_banking_pain_base/__manifest__.py
  account_banking_pain_base/models/account_payment_order.py
Labels: 11.0

#312 Syncing from upstream OCA/bank-payment (11.0)
  account_payment_partner/views/account_invoice_view.xml
Labels: 11.0

#313 Syncing from upstream OCA/bank-payment (12.0)
  account_payment_partner/views/account_invoice_view.xml
Labels: 12.0

#314 Syncing from upstream OCA/bank-payment (12.0)
  account_payment_order/tests/test_account_payment.py
Labels: 12.0

#315 Syncing from upstream OCA/bank-payment (12.0)
  .travis.yml
  account_banking_mandate/i18n/it.po
  account_banking_pain_base/i18n/it.po
Labels: 12.0
