Repository brain-tec/bank-payment, pull requests merged in 2019-06, with the labels that each got.

#329 Syncing from upstream OCA/bank-payment (10.0)
  README.md
  account_banking_mandate/__manifest__.py
  account_banking_mandate/i18n/account_banking_mandate.pot
  account_banking_mandate/i18n/am.po
  account_banking_mandate/i18n/ar.po
  account_banking_mandate/i18n/ca.po
  account_banking_mandate/i18n/cs.po
  account_banking_mandate/i18n/da_DK.po
  account_banking_mandate/i18n/de.po
  account_banking_mandate/i18n/el_GR.po
  account_banking_mandate/i18n/es.po
  account_banking_mandate/i18n/es_CR.po
  account_banking_mandate/i18n/es_EC.po
  account_banking_mandate/i18n/es_ES.po
  account_banking_mandate/i18n/es_MX.po
  account_banking_mandate/i18n/es_VE.po
  account_banking_mandate/i18n/et.po
  account_banking_mandate/i18n/fi.po
  account_banking_mandate/i18n/fr.po
  account_banking_mandate/i18n/gl.po
  account_banking_mandate/i18n/hr.po
  account_banking_mandate/i18n/it.po
  account_banking_mandate/i18n/lt.po
  account_banking_mandate/i18n/nb_NO.po
  account_banking_mandate/i18n/nl.po
  account_banking_mandate/i18n/nl_BE.po
  account_banking_mandate/i18n/nl_NL.po
  account_banking_mandate/i18n/pl.po
  account_banking_mandate/i18n/pt.po
  account_banking_mandate/i18n/pt_BR.po
  account_banking_mandate/i18n/pt_PT.po
  account_banking_mandate/i18n/ro.po
  account_banking_mandate/i18n/ru.po
  account_banking_mandate/i18n/sl.po
  account_banking_mandate/i18n/th.po
  account_banking_mandate/i18n/tr.po
  account_banking_mandate/i18n/vi.po
  account_banking_mandate/migrations/10.0.2.0.0/post-migration.py
  account_banking_mandate/migrations/10.0.2.0.0/pre-migration.py
  account_banking_mandate/models/account_banking_mandate.py
Labels: 10.0

#330 Syncing from upstream OCA/bank-payment (11.0)
  account_banking_mandate/__manifest__.py
  account_banking_mandate/i18n/account_banking_mandate.pot
  account_banking_mandate/i18n/am.po
  account_banking_mandate/i18n/ar.po
  account_banking_mandate/i18n/ca.po
  account_banking_mandate/i18n/cs.po
  account_banking_mandate/i18n/da_DK.po
  account_banking_mandate/i18n/de.po
  account_banking_mandate/i18n/el_GR.po
  account_banking_mandate/i18n/es.po
  account_banking_mandate/i18n/es_CR.po
  account_banking_mandate/i18n/es_EC.po
  account_banking_mandate/i18n/es_ES.po
  account_banking_mandate/i18n/es_MX.po
  account_banking_mandate/i18n/es_VE.po
  account_banking_mandate/i18n/et.po
  account_banking_mandate/i18n/fi.po
  account_banking_mandate/i18n/fr.po
  account_banking_mandate/i18n/gl.po
  account_banking_mandate/i18n/hr.po
  account_banking_mandate/i18n/it.po
  account_banking_mandate/i18n/lt.po
  account_banking_mandate/i18n/nb_NO.po
  account_banking_mandate/i18n/nl.po
  account_banking_mandate/i18n/nl_BE.po
  account_banking_mandate/i18n/pl.po
  account_banking_mandate/i18n/pt.po
  account_banking_mandate/i18n/pt_BR.po
  account_banking_mandate/i18n/pt_PT.po
  account_banking_mandate/i18n/ro.po
  account_banking_mandate/i18n/ru.po
  account_banking_mandate/i18n/sl.po
  account_banking_mandate/i18n/th.po
  account_banking_mandate/i18n/tr.po
  account_banking_mandate/i18n/vi.po
  account_banking_mandate/migrations/11.0.2.0.0/post-migration.py
  account_banking_mandate/migrations/11.0.2.0.0/pre-migration.py
  account_banking_mandate/models/account_banking_mandate.py
Labels: 11.0

#331 Syncing from upstream OCA/bank-payment (12.0)
  account_banking_mandate/__manifest__.py
  account_banking_mandate/i18n/account_banking_mandate.pot
  account_banking_mandate/i18n/am.po
  account_banking_mandate/i18n/ar.po
  account_banking_mandate/i18n/ca.po
  account_banking_mandate/i18n/cs.po
  account_banking_mandate/i18n/da_DK.po
  account_banking_mandate/i18n/de.po
  account_banking_mandate/i18n/el_GR.po
  account_banking_mandate/i18n/es.po
  account_banking_mandate/i18n/es_CR.po
  account_banking_mandate/i18n/es_EC.po
  account_banking_mandate/i18n/es_ES.po
  account_banking_mandate/i18n/es_MX.po
  account_banking_mandate/i18n/es_VE.po
  account_banking_mandate/i18n/et.po
  account_banking_mandate/i18n/fi.po
  account_banking_mandate/i18n/fr.po
  account_banking_mandate/i18n/gl.po
  account_banking_mandate/i18n/hr.po
  account_banking_mandate/i18n/it.po
  account_banking_mandate/i18n/lt.po
  account_banking_mandate/i18n/nb_NO.po
  account_banking_mandate/i18n/nl.po
  account_banking_mandate/i18n/nl_BE.po
  account_banking_mandate/i18n/pl.po
  account_banking_mandate/i18n/pt.po
  account_banking_mandate/i18n/pt_BR.po
  account_banking_mandate/i18n/pt_PT.po
  account_banking_mandate/i18n/ro.po
  account_banking_mandate/i18n/ru.po
  account_banking_mandate/i18n/sl.po
  account_banking_mandate/i18n/th.po
  account_banking_mandate/i18n/tr.po
  account_banking_mandate/i18n/vi.po
  account_banking_mandate/migrations/12.0.2.0.0/post-migration.py
  account_banking_mandate/migrations/12.0.2.0.0/pre-migration.py
  account_banking_mandate/models/account_banking_mandate.py
Labels: 12.0

#332 Syncing from upstream OCA/bank-payment (10.0)
  account_banking_mandate/migrations/10.0.2.0.0/post-migration.py
  account_banking_mandate/migrations/10.0.2.0.0/pre-migration.py
Labels: 10.0

#333 Syncing from upstream OCA/bank-payment (11.0)
  account_banking_mandate/migrations/11.0.2.0.0/post-migration.py
  account_banking_mandate/migrations/11.0.2.0.0/pre-migration.py
Labels: 11.0

#334 Syncing from upstream OCA/bank-payment (12.0)
  account_banking_mandate/migrations/12.0.2.0.0/post-migration.py
  account_banking_mandate/migrations/12.0.2.0.0/pre-migration.py
Labels: 12.0

#336 Syncing from upstream OCA/bank-payment (12.0)
  account_payment_order/__manifest__.py
  account_payment_order/models/account_payment_order.py
Labels: 12.0

#335 [bt#5551] journal_id bug in payment order
  account_payment_order/models/account_payment_order.py
  account_payment_order/views/account_payment_order.xml
Labels: 11.0.project_qt_291
