Repository brain-tec/bank-payment, pull requests merged in 2023-08, with the labels that each got.

#981 Syncing from upstream OCA/bank-payment (14.0)
  README.md
  account_payment_order/__manifest__.py
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order_notification/__manifest__.py
  account_payment_order_notification/data/mail_template_data.xml
  account_payment_order_notification/i18n/account_payment_order_notification.pot
  account_payment_order_notification/i18n/es.po
  account_payment_order_notification/i18n/fr.po
Labels: 14.0

#982 Syncing from upstream OCA/bank-payment (15.0)
  README.md
  account_payment_order/__manifest__.py
  account_payment_order/models/account_payment_order.py
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: 15.0

#983 Syncing from upstream OCA/bank-payment (16.0)
  README.md
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/models/account_banking_mandate.py
Labels: 16.0

#984 Syncing from upstream OCA/bank-payment (10.0)
  account_payment_order/i18n/it.po
Labels: 10.0

#985 Syncing from upstream OCA/bank-payment (14.0)
  account_payment_order/i18n/it.po
Labels: 14.0

#986 Syncing from upstream OCA/bank-payment (10.0)
  account_payment_order/i18n/it.po
Labels: 10.0

#987 Syncing from upstream OCA/bank-payment (11.0)
  account_payment_order/i18n/it.po
Labels: 11.0

#988 Syncing from upstream OCA/bank-payment (12.0)
  account_banking_mandate/i18n/it.po
  account_payment_partner/i18n/it.po
Labels: 12.0

#989 Syncing from upstream OCA/bank-payment (13.0)
  account_banking_mandate/i18n/it.po
Labels: 13.0

#990 Syncing from upstream OCA/bank-payment (14.0)
  account_banking_mandate/i18n/it.po
  account_payment_order/i18n/it.po
Labels: 14.0

#991 Syncing from upstream OCA/bank-payment (15.0)
  account_banking_mandate/i18n/it.po
Labels: 15.0

#992 Syncing from upstream OCA/bank-payment (16.0)
  account_banking_mandate/i18n/it.po
Labels: 16.0

#993 Syncing from upstream OCA/bank-payment (14.0)
  account_payment_partner/i18n/it.po
Labels: 14.0

#995 Syncing from upstream OCA/bank-payment (15.0)
  README.md
  account_payment_order/__manifest__.py
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/models/account_move.py
Labels: 15.0

#996 Syncing from upstream OCA/bank-payment (16.0)
  README.md
  account_payment_order/__manifest__.py
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/models/account_move.py
Labels: 16.0

#997 [t140653] Improving tests account_banking_sepa_credit_transfer
  account_banking_sepa_credit_transfer/tests/test_sct.py
Labels: 16.0.project_xp_228
