Repository brain-tec/bank-payment, pull requests merged in 2024-07, with the labels that each got.

#1236 Syncing from upstream OCA/bank-payment (15.0)
  README.md
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/i18n/am.po
  account_payment_order/i18n/ar.po
  account_payment_order/i18n/ca.po
  account_payment_order/i18n/ca_ES.po
  account_payment_order/i18n/cs.po
  account_payment_order/i18n/da_DK.po
  account_payment_order/i18n/de.po
  account_payment_order/i18n/el_GR.po
  account_payment_order/i18n/es.po
  account_payment_order/i18n/es_AR.po
  account_payment_order/i18n/es_CL.po
  account_payment_order/i18n/es_CR.po
  account_payment_order/i18n/es_EC.po
  account_payment_order/i18n/es_ES.po
  account_payment_order/i18n/es_MX.po
  account_payment_order/i18n/es_VE.po
  account_payment_order/i18n/et.po
  account_payment_order/i18n/fi.po
  account_payment_order/i18n/fr.po
  account_payment_order/i18n/fr_FR.po
  account_payment_order/i18n/gl.po
  account_payment_order/i18n/hr.po
  account_payment_order/i18n/it.po
  account_payment_order/i18n/lt.po
  account_payment_order/i18n/nb_NO.po
  account_payment_order/i18n/nl.po
  account_payment_order/i18n/nl_BE.po
  account_payment_order/i18n/nl_NL.po
  account_payment_order/i18n/pl.po
  account_payment_order/i18n/pt.po
  account_payment_order/i18n/pt_BR.po
  account_payment_order/i18n/pt_PT.po
  account_payment_order/i18n/ro.po
  account_payment_order/i18n/ru.po
  account_payment_order/i18n/sl.po
  account_payment_order/i18n/sv.po
  account_payment_order/i18n/th.po
  account_payment_order/i18n/tr.po
  account_payment_order/i18n/vi.po
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/models/account_payment_mode.py
  account_payment_order/static/description/index.html
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_payment_mode.xml
Labels: 15.0

#1237 Syncing from upstream OCA/bank-payment (16.0)
  README.md
  account_banking_pain_base/README.rst
  account_banking_pain_base/__manifest__.py
  account_banking_pain_base/i18n/sv.po
  account_banking_pain_base/static/description/index.html
  account_payment_purchase/README.rst
  account_payment_purchase/__manifest__.py
  account_payment_purchase/models/purchase_order.py
  account_payment_purchase/static/description/index.html
  account_payment_purchase/tests/test_account_payment_purchase.py
Labels: 16.0

#1238 Syncing from upstream OCA/bank-payment (16.0)
  README.md
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/i18n/es.po
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/static/description/index.html
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_payment_line.xml
Labels: 16.0

#1239 Syncing from upstream OCA/bank-payment (17.0)
  README.md
  account_banking_sepa_direct_debit/README.rst
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/static/description/index.html
  account_banking_sepa_direct_debit/tests/test_sdd.py
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/models/account_move.py
  account_payment_order/static/description/index.html
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_purchase/README.rst
  account_payment_purchase/__manifest__.py
  account_payment_purchase/models/purchase_order.py
  account_payment_purchase/static/description/index.html
  account_payment_purchase/tests/test_account_payment_purchase.py
Labels: 17.0

#1240 Syncing from upstream OCA/bank-payment (14.0)
  README.md
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/i18n/es.po
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/static/description/index.html
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
Labels: 14.0

#1241 Syncing from upstream OCA/bank-payment (16.0)
  account_payment_order/i18n/it.po
Labels: 16.0

#1235 [t140653] Add migration scripts from 15, and adapt them
  account_payment_order/migrations/15.0.2.0.0/post-migration.py
  account_payment_order/migrations/15.0.2.0.0/pre-migration.py
Labels: 16.0.project_xp_228

#1242 Syncing from upstream OCA/bank-payment (15.0)
  README.md
  account_banking_sepa_credit_transfer/README.rst
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_credit_transfer/static/description/index.html
  account_banking_sepa_direct_debit/README.rst
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/models/account_payment_order.py
  account_banking_sepa_direct_debit/static/description/index.html
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/i18n/am.po
  account_payment_order/i18n/ar.po
  account_payment_order/i18n/ca.po
  account_payment_order/i18n/ca_ES.po
  account_payment_order/i18n/cs.po
  account_payment_order/i18n/da_DK.po
  account_payment_order/i18n/de.po
  account_payment_order/i18n/el_GR.po
  account_payment_order/i18n/es.po
  account_payment_order/i18n/es_AR.po
  account_payment_order/i18n/es_CL.po
  account_payment_order/i18n/es_CR.po
  account_payment_order/i18n/es_EC.po
  account_payment_order/i18n/es_ES.po
  account_payment_order/i18n/es_MX.po
  account_payment_order/i18n/es_VE.po
  account_payment_order/i18n/et.po
  account_payment_order/i18n/fi.po
  account_payment_order/i18n/fr.po
  account_payment_order/i18n/fr_FR.po
  account_payment_order/i18n/gl.po
  account_payment_order/i18n/hr.po
  account_payment_order/i18n/it.po
  account_payment_order/i18n/lt.po
  account_payment_order/i18n/nb_NO.po
  account_payment_order/i18n/nl.po
  account_payment_order/i18n/nl_BE.po
  account_payment_order/i18n/nl_NL.po
  account_payment_order/i18n/pl.po
  account_payment_order/i18n/pt.po
  account_payment_order/i18n/pt_BR.po
  account_payment_order/i18n/pt_PT.po
  account_payment_order/i18n/ro.po
  account_payment_order/i18n/ru.po
  account_payment_order/i18n/sl.po
  account_payment_order/i18n/sv.po
  account_payment_order/i18n/th.po
  account_payment_order/i18n/tr.po
  account_payment_order/i18n/vi.po
  account_payment_order/models/account_payment.py
  account_payment_order/static/description/index.html
  account_payment_order/tests/test_payment_order_inbound.py
Labels: 15.0

#1243 Syncing from upstream OCA/bank-payment (17.0)
  .copier-answers.yml
  .eslintrc.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/i18n/es.po
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/static/description/index.html
  account_payment_order/tests/test_payment_order_inbound.py
  account_payment_order/tests/test_payment_order_outbound.py
  account_payment_order/views/account_payment_line.xml
Labels: 17.0

#1244 Syncing from upstream OCA/bank-payment (14.0)
  README.md
  account_banking_sepa_credit_transfer/README.rst
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_credit_transfer/static/description/index.html
  account_banking_sepa_direct_debit/README.rst
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/models/account_payment_order.py
  account_banking_sepa_direct_debit/static/description/index.html
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/i18n/am.po
  account_payment_order/i18n/ar.po
  account_payment_order/i18n/ca.po
  account_payment_order/i18n/ca_ES.po
  account_payment_order/i18n/cs.po
  account_payment_order/i18n/da_DK.po
  account_payment_order/i18n/de.po
  account_payment_order/i18n/el_GR.po
  account_payment_order/i18n/es.po
  account_payment_order/i18n/es_AR.po
  account_payment_order/i18n/es_CL.po
  account_payment_order/i18n/es_CR.po
  account_payment_order/i18n/es_EC.po
  account_payment_order/i18n/es_ES.po
  account_payment_order/i18n/es_MX.po
  account_payment_order/i18n/es_VE.po
  account_payment_order/i18n/et.po
  account_payment_order/i18n/fi.po
  account_payment_order/i18n/fr.po
  account_payment_order/i18n/gl.po
  account_payment_order/i18n/hr.po
  account_payment_order/i18n/it.po
  account_payment_order/i18n/lt.po
  account_payment_order/i18n/nb_NO.po
  account_payment_order/i18n/nl.po
  account_payment_order/i18n/nl_BE.po
  account_payment_order/i18n/nl_NL.po
  account_payment_order/i18n/pl.po
  account_payment_order/i18n/pt.po
  account_payment_order/i18n/pt_BR.po
  account_payment_order/i18n/pt_PT.po
  account_payment_order/i18n/ro.po
  account_payment_order/i18n/ru.po
  account_payment_order/i18n/sl.po
  account_payment_order/i18n/sv.po
  account_payment_order/i18n/th.po
  account_payment_order/i18n/tr.po
  account_payment_order/i18n/vi.po
  account_payment_order/models/account_payment.py
  account_payment_order/static/description/index.html
  account_payment_order/tests/test_payment_order_inbound.py
Labels: 14.0

#1245 Syncing from upstream OCA/bank-payment (16.0)
  account_payment_partner/i18n/ca.po
Labels: 16.0

#1246 Syncing from upstream OCA/bank-payment (14.0)
  README.md
  account_invoice_select_for_payment/README.rst
  account_invoice_select_for_payment/__manifest__.py
  account_invoice_select_for_payment/static/description/index.html
  account_invoice_select_for_payment/views/account_move.xml
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/models/account_payment.py
  account_payment_order/static/description/index.html
Labels: 14.0

#1247 Syncing from upstream OCA/bank-payment (16.0)
  README.md
  account_banking_sepa_credit_transfer/README.rst
  account_banking_sepa_credit_transfer/__manifest__.py
  account_banking_sepa_credit_transfer/models/account_payment_order.py
  account_banking_sepa_credit_transfer/static/description/index.html
  account_banking_sepa_direct_debit/README.rst
  account_banking_sepa_direct_debit/__manifest__.py
  account_banking_sepa_direct_debit/models/account_payment_order.py
  account_banking_sepa_direct_debit/static/description/index.html
  account_payment_order/README.rst
  account_payment_order/__manifest__.py
  account_payment_order/i18n/account_payment_order.pot
  account_payment_order/i18n/am.po
  account_payment_order/i18n/ar.po
  account_payment_order/i18n/ca.po
  account_payment_order/i18n/ca_ES.po
  account_payment_order/i18n/cs.po
  account_payment_order/i18n/da_DK.po
  account_payment_order/i18n/de.po
  account_payment_order/i18n/el_GR.po
  account_payment_order/i18n/es.po
  account_payment_order/i18n/es_AR.po
  account_payment_order/i18n/es_CL.po
  account_payment_order/i18n/es_CR.po
  account_payment_order/i18n/es_EC.po
  account_payment_order/i18n/es_ES.po
  account_payment_order/i18n/es_MX.po
  account_payment_order/i18n/es_VE.po
  account_payment_order/i18n/et.po
  account_payment_order/i18n/fi.po
  account_payment_order/i18n/fr.po
  account_payment_order/i18n/fr_FR.po
  account_payment_order/i18n/gl.po
  account_payment_order/i18n/hr.po
  account_payment_order/i18n/it.po
  account_payment_order/i18n/lt.po
  account_payment_order/i18n/nb_NO.po
  account_payment_order/i18n/nl.po
  account_payment_order/i18n/nl_BE.po
  account_payment_order/i18n/nl_NL.po
  account_payment_order/i18n/pl.po
  account_payment_order/i18n/pt.po
  account_payment_order/i18n/pt_BR.po
  account_payment_order/i18n/pt_PT.po
  account_payment_order/i18n/ro.po
  account_payment_order/i18n/ru.po
  account_payment_order/i18n/sl.po
  account_payment_order/i18n/sv.po
  account_payment_order/i18n/th.po
  account_payment_order/i18n/tr.po
  account_payment_order/i18n/vi.po
  account_payment_order/models/account_move.py
  account_payment_order/models/account_payment.py
  account_payment_order/models/account_payment_line.py
  account_payment_order/static/description/index.html
  account_payment_order/tests/test_payment_order_inbound.py
Labels: 16.0

#1250 Syncing from upstream OCA/bank-payment (17.0)
  account_vendor_bank_account_default/i18n/it.po
Labels: 17.0

#1251 Syncing from upstream OCA/bank-payment (15.0)
  README.md
  account_banking_mandate/README.rst
  account_banking_mandate/__manifest__.py
  account_banking_mandate/models/account_banking_mandate.py
  account_banking_mandate/static/description/index.html
  account_banking_mandate/tests/test_mandate.py
Labels: 15.0

#1252 Syncing from upstream OCA/bank-payment (16.0)
  README.md
  account_banking_mandate/README.rst
  account_banking_mandate/__manifest__.py
  account_banking_mandate/i18n/ca.po
  account_banking_mandate/models/account_banking_mandate.py
  account_banking_mandate/static/description/index.html
  account_banking_mandate/tests/test_mandate.py
Labels: 16.0

#1253 Syncing from upstream OCA/bank-payment (17.0)
  README.md
  account_payment_mode/README.rst
  account_payment_mode/__manifest__.py
  account_payment_mode/models/account_journal.py
  account_payment_mode/static/description/index.html
  account_payment_purchase/README.rst
  account_payment_purchase/__manifest__.py
  account_payment_purchase/models/account_move.py
  account_payment_purchase/models/purchase_order.py
  account_payment_purchase/static/description/index.html
Labels: 17.0
